[project]
name = ""
version = ""
description = ""
authors = [
    {name = "wedley", email = "wedleysilva2105@gmail.com"},
]
dependencies = [
    "django>=4.2.4",
    "djangorestframework>=3.14.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
