# Generated by Django 4.2 on 2023-04-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garagem.categoria')),
                ('Cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garagem.cor')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garagem.marca')),
                ('Modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garagem.modelo')),
            ],
        ),
    ]
