# Generated by Django 4.2.1 on 2023-05-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_nome_veiculo_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nome',
            new_name='Modelo',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Cor',
            new_name='cor',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='preco',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Modelo',
            new_name='modelo',
        ),
    ]
