# Generated by Django 4.2.1 on 2023-05-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0006_alter_acessorio_options_alter_cor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='Nome',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='garagem.modelo'),
            preserve_default=False,
        ),
    ]
